version: 2
jobs:
  plan:
    docker:
      - image: docker.io/mataly/toolbox-rs-pipeline-python:latest
    steps:
      - checkout
      - run: 
          command: python3 /rackspace/check_authentication.py
          name: Check Authentication  
      - run: 
          command: python3 /rackspace/plan.py
          name: Terraform Plan

workflows:
  version: 2
  build_and_test:
    jobs:
      - plan