version: 2
jobs:
  plan:
    working_directory: /rackspace
    docker:
      - image: docker.io/mataly/toolbox-rs-pipeline-python:latest
    steps:
      - checkout
      - run: python3 authenticate.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - plan