version: 2
jobs:
  plan:
    docker:
      - image: registry.hub.docker.com/r/mataly/toolbox-rs-pipeline-python:latest
    steps:
      - checkout
      - run: authenticate.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - plan