version: 2
jobs:
  plan:
    parameters:
      continue_apply:
        type: env_var_name
        default: False
    docker:
      - image: docker.io/mataly/toolbox-rs-pipeline-python:latest
    steps:
      - checkout
      - run: 
          command: python3 /rackspace/check_authentication.py
          name: Check Authentication  
      - run: 
          command: python3 /rackspace/plan.py >> ${<< parameters.continue_apply >>}
          name: Terraform Plan
      - run: 
          command: echo ${<< parameters.continue_apply >>}
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: workspace
          paths:
            - .terraform.*.tar.gz
            - terraform.*.plan
            - layers

  apply:
    docker:
      - image: docker.io/mataly/toolbox-rs-pipeline-python:latest
    steps:
      - run: 
          command: python3 /rackspace/check_authentication.py
          name: Check Authentication
      - attach_workspace:
          at: workspace
      - run: 
          command: python3 /rackspace/apply.py
          name: Terraform Apply
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - plan
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: master