version: 2.1
jobs:
  plan:
    docker:
      - image: docker.io/mataly/toolbox-rs-pipeline-python:latest
    steps:
      - checkout
      - run: 
          command: python3 /rackspace/check_authentication.py
          name: Check Authentication  
      - run: 
          command: python3 /rackspace/plan.py >> workspace/continue_apply
          name: Terraform Plan
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: workspace
          paths:
            - continue_apply
            - .terraform.*.tar.gz
            - terraform.*.plan
            - layers

  apply:
    docker:
      - image: docker.io/mataly/toolbox-rs-pipeline-python:latest
    steps:
      - run:
          command: echo ./continue_apply
      - run: 
          command: python3 /rackspace/check_authentication.py
          name: Check Authentication
      - attach_workspace:
          at: workspace
      - run: 
          command: python3 /rackspace/apply.py
          name: Terraform Apply
      
workflows:
  build_and_test:
    jobs:
      - plan
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: master
    